name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run backend tests
        run: ./gradlew test --no-daemon

      - name: Upload backend test report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-report
          path: build/reports/tests/test

      - name: Upload backend test results (JUnit XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results-xml
          path: build/test-results/test
